version: '3'

services:
  app:
    build: .
    ports:
      - "5804:5804"
    depends_on:
      - mongo
    environment:
      - PORT=5804
    networks:
      - my-network

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    networks:
      - my-network

volumes:
  data:

networks:
  my-network:
